### ISSUE TITLE
Develop basic checklist for software systems using PreFlight

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#1032]
### What needs to change?

This should be the start of a checklist that helps us to ensure that all software systems are working. Some parts of this checklist can be manual, while other parts of the checklist can be automatic if desired.

This checklist should include:
* Ensuring that cameras are functioning as expected
* Ensuring that the CPU is not too hot
* Ensuring that all boards are plugged in/found
* Ensuring that other sensors are plugged in

This will be the start of the PreFlight system, meaning that whoever takes on this task can also help to determine the future direction of this project.

### How would this task be tested?

1. Write some basic tests for the PreFlight system. 

### Contacts

- [ ] We need help from the mechanical team.
- [ ] We need help from the electrical team.
- [ ] We need help from Dr. Schwartz or other faculty.
- [ ] We need help from a company or an organization.
- [ ] We need help from another UF staff member or organization (ex, facilities).
